export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
export const AUTH_INPUT_CHANGE = 'AUTH_INPUT_CHANGE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOADING = 'LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_FAILURE = 'SIGNUP_FAILURE';
export const AUTH_ADD_CONTENT = 'AUTH_ADD_CONTENT';
export const ADD_CONTENT_FAILURE = 'ADD_CONTENT_FAILURE';
export const ADD_CONTENT_SUCCESS = 'ADD_CONTENT_SUCCESS';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAILURE = 'PROFILE_UPDATE_FAILURE';
export const SUBMIT_HELP_SUCCESS = 'SUBMIT_HELP_SUCCESS';
export const SUBMIT_HELP_FAILURE = 'SUBMIT_HELP_FAILURE';

